apiVersion: apps/v1
kind: Deployment
metadata:
  name: shop
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: shop
  template:
    metadata:
      labels:
        io.kompose.service: shop
    spec:
      containers:
        - name: shop
          image: digitalreceipts/shop
          imagePullPolicy: Always
          ports:
            - containerPort: 9000
              protocol: TCP
          resources: {}
          env:
          - name: CA_DB_HOST
            value: hash-registry-rethinkdb
          - name: CA_DB_PORT
            value: "28015"
          - name: SHOP_URL
            value: http://shop
          - name: MAIL_URL
            value: http://user-email
          - name: USER_ACCOUNTING_URL
            value: http://user-accounting
          - name: HASH_REGISTRY_URL
            value: http://hash-registry-poc
          - name: CA_URL
            value: http://ca
          - name: PUBLISHER_ORG_ID
            value: "123"
          - name: USER_ACCOUNTING_ORG_ID
            value: "456"
          - name: SHOP_PORT
            value: "9000"
          - name: HASH_GENERATOR_URL
            value: http://hash-generator
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: shop
  labels:
    io.kompose.service: shop
spec:
  ports:
    - name: "80"
      protocol: TCP
      port: 80
      targetPort: 9000
  selector:
    io.kompose.service: shop
  type: ClusterIP
status:
  loadBalancer: {}
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: shop
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
    - host: shop.digitala-kvitton.se
      http:
        paths:
          - backend:
              serviceName: shop
              servicePort: 80
status:
  loadBalancer: {}
