apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-email
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: user-email
  template:
    metadata:
      labels:
        io.kompose.service: user-email
    spec:
      containers:
        - name: user-email
          image: digitalreceipts/user-email
          imagePullPolicy: Always
          ports:
            - containerPort: 7900
              protocol: TCP
          resources:
            limits:
              cpu: 100m
              memory: 100Mi
          env:
            - name: SHOP_URL
              value: http://shop
            - name: MAIL_URL
              value: http://user-email
            - name: USER_ACCOUNTING_URL
              value: https://user-accounting.digitala-kvitton.se
            - name: HASH_REGISTRY_URL
              value: http://hash-registry-poc
            - name: CA_URL
              value: http://ca
            - name: PUBLISHER_ORG_ID
              value: '123'
            - name: USER_ACCOUNTING_ORG_ID
              value: '456'
            - name: USER_ACCOUNTING_URL_EXT
              value: 'https://user-accounting.digitala-kvitton.se'
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: user-email
  labels:
    io.kompose.service: user-email
spec:
  ports:
    - name: '80'
      protocol: TCP
      port: 80
      targetPort: 7900
  selector:
    io.kompose.service: user-email
  type: ClusterIP
status:
  loadBalancer: {}
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: user-email
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
    - host: user-email.digitala-kvitton.se
      http:
        paths:
          - backend:
              serviceName: user-email
              servicePort: 80
status:
  loadBalancer: {}
