---
version: '3'

services:
  ca-rethinkdb:
    image: rethinkdb:2.3.6
    ports:
      - 127.0.0.1:8081:8080
      - 127.0.0.1:28016:28015
    networks:
      digital-receipts:
        aliases:
          - ca-rethinkdb

networks:
  digital-receipts:
    external:
      name: digital-receipts
